// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AceEditorController from "./ace_editor_controller"
application.register("ace-editor", AceEditorController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HighlightCodeBlockController from "./highlight_code_block_controller"
application.register("highlight-code-block", HighlightCodeBlockController)

import InlineCodeTrixController from "./inline_code_trix_controller"
application.register("inline-code-trix", InlineCodeTrixController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

// Used in header component for avatar dropdown
import Dropdown from "@stimulus-components/dropdown"
application.register("dropdown", Dropdown)

// Used in main layout with header and sidebar components
import Sidebar from "./sidebar_controller"
application.register("sidebar", Sidebar)
