plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: true

# Double quotes are preffered for string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We always treat strings as frozen
Style/FrozenStringLiteralComment:
  EnforcedStyle: never