plugins:
  - rubocop-rails
  - rubocop-rspec

require:
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: true

# Double quotes are preffered for string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We always treat strings as frozen
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# We treat some blocks as one line
Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

# We don't need to use underscores in numbers
Style/NumericLiterals:
  Enabled: false