plugins:
  - rubocop-rails
  - rubocop-rspec

require:
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/factories/**/*'

# Double quotes are preffered for string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We always treat strings as frozen
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# We treat some blocks as one line
Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

# We don't need to use underscores in numbers
Style/NumericLiterals:
  Enabled: false